# Generated by Django 4.0.2 on 2022-04-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comments_listing_alter_comments_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='image_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
